import { CalendarCheck, CircleDollarSign, Scissors, Store } from "lucide-react";
import { redirect } from "next/navigation";
import { getSession } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { clp } from "@/lib/data";
import { formatChileTime } from "@/lib/time";

export default async function AdminDashboard() {
  const session = await getSession();
  if (session?.role === "BARBER") redirect("/admin/reservas");
  const start=new Date();start.setHours(0,0,0,0);const end=new Date();end.setHours(23,59,59,999);
  const weekStart=new Date(start);weekStart.setDate(start.getDate()-start.getDay());const monthStart=new Date(start.getFullYear(),start.getMonth(),1);
  const [todayCount,weekCount,monthCount,pendingCount,cancelledCount,noShowCount,sales,barberCount,branchCount,upcoming,lowStock,newCustomers,recurringCustomers,barbers,topProducts]=await Promise.all([
    prisma.appointment.count({where:{startAt:{gte:start,lte:end}}}),prisma.appointment.count({where:{startAt:{gte:weekStart}}}),prisma.appointment.count({where:{startAt:{gte:monthStart}}}),prisma.appointment.count({where:{status:"PENDING"}}),prisma.appointment.count({where:{status:"CANCELLED",startAt:{gte:monthStart}}}),prisma.appointment.count({where:{status:"NO_SHOW",startAt:{gte:monthStart}}}),
    prisma.order.aggregate({where:{createdAt:{gte:start,lte:end},status:{not:"CANCELLED"}},_sum:{total:true}}),prisma.barber.count({where:{active:true}}),prisma.branch.count({where:{active:true}}),
    prisma.appointment.findMany({where:{startAt:{gte:new Date()},status:{in:["PENDING","CONFIRMED"]}},include:{customer:true,barber:true,service:true,branch:true},orderBy:{startAt:"asc"},take:5}),prisma.product.findMany({where:{stock:{lte:6},status:"ACTIVE"},orderBy:{stock:"asc"},take:5}),
    prisma.customer.count({where:{createdAt:{gte:monthStart}}}),prisma.customer.count({where:{visitCount:{gte:2}}}),
    prisma.barber.findMany({where:{active:true},include:{_count:{select:{appointments:true}},appointments:{where:{status:"COMPLETED"},include:{service:true}},reviews:true}}),
    prisma.orderItem.groupBy({by:["productId","name"],_sum:{quantity:true,total:true},orderBy:{_sum:{quantity:"desc"}},take:5})
  ]);
  const ranking=barbers.map(b=>({name:`${b.firstName} ${b.lastName}`,reservations:b._count.appointments,completed:b.appointments.length,revenue:b.appointments.reduce((s,a)=>s+a.service.price,0),rating:b.reviews.length?b.reviews.reduce((s,r)=>s+r.rating,0)/b.reviews.length:0})).sort((a,b)=>b.reservations-a.reservations);
  const max=Math.max(todayCount,weekCount,monthCount,1);
  return <><header className="admin-top"><div><h1>Buenos días, {session?.name.split(" ")[0]}</h1><p>Este es el pulso de Vikingos hoy.</p></div><div className="admin-user"><div><strong>{session?.name}</strong><small style={{display:"block",color:"#777"}}>{session?.role}</small></div><span className="avatar">{session?.name.slice(0,2).toUpperCase()}</span></div></header>
  <section className="metrics"><div className="metric"><div className="metric-head"><span>Reservas de hoy</span><span className="metric-icon"><CalendarCheck size={18}/></span></div><strong>{todayCount}</strong><small>{pendingCount} pendientes</small></div><div className="metric"><div className="metric-head"><span>Ventas del día</span><span className="metric-icon"><CircleDollarSign size={18}/></span></div><strong>{clp(sales._sum.total||0)}</strong><small>Órdenes no canceladas</small></div><div className="metric"><div className="metric-head"><span>Barberos activos</span><span className="metric-icon"><Scissors size={18}/></span></div><strong>{barberCount}</strong><small>Disponibles</small></div><div className="metric"><div className="metric-head"><span>Sucursales</span><span className="metric-icon"><Store size={18}/></span></div><strong>{branchCount}</strong><small>Operativas</small></div></section>
  <section className="admin-grid"><div className="panel"><h2>Próximas reservas</h2>{upcoming.map(a=><div className="appointment-row" key={a.id}><strong className="appointment-time">{formatChileTime(a.startAt)}</strong><div><strong>{a.customer.name}</strong><span>{a.service.name}</span></div><div><strong>{a.barber.firstName} {a.barber.lastName}</strong><span>{a.branch.name}</span></div><span className="status">{a.status}</span></div>)}</div><div className="panel"><h2>Stock bajo</h2>{lowStock.map(p=><div className="stock-row" key={p.id}><img src={p.image||"/placeholder-product.svg"} alt=""/><div><strong>{p.name}</strong><small style={{display:"block",color:"#888"}}>{p.brand}</small></div><span>{p.stock} un.</span></div>)}</div></section>
  <section className="advanced-dashboard-grid"><div className="panel"><h2>Rendimiento de reservas</h2><div className="bar-chart">{[["Hoy",todayCount],["Semana",weekCount],["Mes",monthCount]].map(([label,value])=><div className="bar-column" key={String(label)}><strong>{value}</strong><div style={{height:`${Math.max(8,Number(value)/max*150)}px`}}/><span>{label}</span></div>)}</div><div className="dashboard-mini-metrics"><span>Clientes nuevos <strong>{newCustomers}</strong></span><span>Recurrentes <strong>{recurringCustomers}</strong></span><span>Canceladas <strong>{cancelledCount}</strong></span><span>No show <strong>{noShowCount}</strong></span></div></div>
  <div className="panel"><h2>Ranking de barberos</h2>{ranking.map((b,i)=><div className="ranking-row" key={b.name}><span className="rank-number">{i+1}</span><div><strong>{b.name}</strong><small>{b.reservations} reservas · {b.completed} atendidas</small></div><div><strong>{clp(b.revenue)}</strong><small>{b.rating?`★ ${b.rating.toFixed(1)}`:"Sin valoraciones"}</small></div></div>)}</div>
  <div className="panel"><h2>Productos más vendidos</h2>{topProducts.map((p,i)=><div className="ranking-row" key={p.productId}><span className="rank-number">{i+1}</span><div><strong>{p.name}</strong><small>{p._sum.quantity||0} unidades</small></div><strong>{clp(p._sum.total||0)}</strong></div>)}</div></section></>;
}
